website_dir = "../website"
challenges_dir = "../desafios"
template_dir = "./templates"

# Ignore these users completely (admins, etc)
ignore_users = ["bernardinocampos", "marcopaganini", "mpinheir", "qrwteyrutiyoup"]

# Number of points for each of the desafio-NN entries. Specify
# [points.desafio-NN] for a given entry, with "value" representing the number
# of points to assign if a given person finished that particular challenge.

[points]
  [points.desafio-01]
  value = 10

  [points.desafio-02]
  value = 20

  [points.desafio-03]
  value = 20

  [points.desafio-04]
  value = 20

  [points.desafio-05]
  value = 50

  [points.desafio-06]
  value = 70

  [points.desafio-07]
  value = 50

  [points.desafio-08]
  value = 30

  [points.desafio-09]
  value = 30

  [points.desafio-10]
  value = 60

  [points.desafio-11]
  value = 60

  [points.desafio-12]
  value = 30

  [points.desafio-13]
  value = 50

  [points.desafio-14]
  value = 40
