name: 'Close stale PRs'
on:
  schedule:
    - cron: '50 23 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-pr-message: 'PR marcado como obsoleto devido à falta de atividade. Fechamento automático ocorrerá em 5 dias na ausência de nova atividade.'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'awaiting-approval,work-in-progress'
          days-before-pr-stale: 12
          days-before-pr-close: 5
          days-before-issue-stale: -1

